import os
from typing import List, Literal
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field


class ClinicalReportSchema(BaseModel):
  modality: str = Field(
      description="Detected medical imaging modality (e.g. Chest X-Ray, Brain MRI)"
  )
  primary_diagnosis_impression: str = Field(
      description="Clear, authoritative diagnostic impression of primary finding"
  )
  urgency_level: Literal["Routine", "Expedited", "Immediate / Emergency"] = (
      Field(
          description="Triage urgency based on detected visual abnormalities"
      )
  )
  key_visual_evidence: List[str] = Field(
      description="Specific visual biomarkers and observations extracted from the scan"
  )
  differential_diagnoses: List[str] = Field(
      description="Ranked list of alternative clinical possibilities"
  )
  recommended_next_steps: List[str] = Field(
      description="Actionable next steps (e.g., confirmatory imaging, lab work, specialist referral)"
  )
  clinical_disclaimer: str = Field(
      default="Decision-support analysis generated by AI. Requires verification by a certified medical specialist.",
      description="Standard non-diagnostic safety disclaimer",
  )


class ClinicalReportGenerator:

  def __init__(self, api_key: str = None):
    self.groq_api_key = api_key or os.getenv("GROQ_API_KEY")
    self.llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        groq_api_key=self.groq_api_key,
        temperature=0.0,
    ).with_structured_output(ClinicalReportSchema)

    self.prompt = ChatPromptTemplate.from_messages([
        (
            "system",
            (
                "You are an Autonomous AI Radiologist & Medical Decision Support Agent.\n"
                "Your objective is to review zero-shot vision extractor data and synthesize a structured, professional clinical report.\n"
                "Constraints:\n"
                "1. Base findings strictly on provided visual feature extractor outputs.\n"
                "2. Maintain professional medical terminology (e.g., opacities, consolidation, radiolucency).\n"
                "3. Flag severe conditions (e.g., tension pneumothorax, intracranial hemorrhage) with 'Immediate / Emergency' urgency."
            ),
        ),
        (
            "human",
            (
                "Patient History / Context:\n{patient_context}\n\n"
                "BiomedCLIP Vision Extractor Data:\n{vision_data}\n\n"
                "Generate the structured diagnostic report:"
            ),
        ),
    ])

    self.chain = self.prompt | self.llm

  def generate(
      self, vision_data: dict, patient_context: str = "No prior history provided."
  ) -> ClinicalReportSchema:
    return self.chain.invoke({
        "vision_data": str(vision_data),
        "patient_context": patient_context,
    })
